name: Main - Test and Deploy to NPM

on:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install everything
        run: npm install
      - name: Run Unit tests
        run: npm test
      - name: Publish to NPM
        run: npm publish --access public
        env:
          token: ${{ secrets.NPM_TOKEN }}